my_project
settings __init__.py, dev.py, prod.py
mainapp __init__.py, models.py, views.py
mainapp\templates\mainapp
authapp __init__.py, models.py, views.py
authapp\templates\authapp base.html, views.html
